core.repository=https://github.com/HuanHuanHuanFFF/WindLetter.git
core.commit=4a5e9a747148fd05940e7571ff4cc80f014a4127
core.groupId=com.windletter
core.artifactId=windletter-api
core.version=0.1.0-SNAPSHOT
