core.repository=https://github.com/HuanHuanHuanFFF/WindLetter.git
core.commit=15677e77f53cc2b6b8b765d124cd3f5cb1023594
core.groupId=com.windletter
core.artifactId=windletter-api
core.version=0.1.0-SNAPSHOT
